name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      uses: actions/checkout@v4

    - id: setup-python
      name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - id: install-poetry
      name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - id: install-dependencies
      name: Install dependencies
      run: poetry install

    - id: run-tests
      name: Run tests with coverage
      run: poetry run pytest --cov=dora_lead_time tests/

    - id: upload-coverage
      name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
