name: Build and Test

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      uses: actions/checkout@v4

    - id: setup-python
      name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - id: install-poetry
      name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry --version

    - id: install-dependencies
      name: Install dependencies
      run: poetry install

    - id: check-compilation
      name: Check code compilation
      run: |
        echo "Checking Python syntax..."
        poetry run python -m compileall -q .
        echo "Python syntax check completed successfully"

    - id: run-tests
      name: Run tests with coverage
      run: |
        echo "Running tests with coverage..."
        poetry run pytest --cov=. --cov-report=term --cov-report=xml --cov-report=html
        echo "Tests completed successfully"

    - id: upload-coverage-report
      name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: |
          coverage.xml
          htmlcov/
        if-no-files-found: warn
