name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      uses: actions/checkout@v4

    - id: setup-python
      name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - id: install-poetry
      name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - id: install-dependencies
      name: Install dependencies
      run: poetry install

    - id: check-compilation
      name: Check code compilation
      run: |
        echo "Checking Python syntax..."
        poetry run python -m compileall -q .
        echo "Python syntax check completed successfully"

    - id: run-tests
      name: Run tests
      run: |
        echo "Running tests..."
        poetry run pytest
        echo "Tests completed successfully"
